name: unit tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - .github/workflows/docs.yml
      - .github/workflows/unit_tests.yml
      - '**.py'
      - '**.ipynb'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82
        with:
          # Install a specific version of uv.
          version: "0.9.22"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        run: |
          cd aieng-eval-agents
          uv run pytest -m "not integration_test" --cov aieng/agent_evals --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: VectorInstitute/eval-agents
          fail_ci_if_error: false
          verbose: true
